wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707748025.523308
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 105
      3:
      - 23
      4: 3.9.18
      5: 0.16.3
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
pretrained_model_name_or_path:
  desc: null
  value: riffusion/riffusion-model-v1
controlnet_model_name_or_path:
  desc: null
  value: null
revision:
  desc: null
  value: null
variant:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
output_dir:
  desc: null
  value: /mnt/g/data/output/lr2.56e-3_gas256/models
cache_dir:
  desc: null
  value: /mnt/d/data/cache
seed:
  desc: null
  value: null
resolution:
  desc: null
  value: 512
train_batch_size:
  desc: null
  value: 4
num_train_epochs:
  desc: null
  value: 1
max_train_steps:
  desc: null
  value: 612
checkpointing_steps:
  desc: null
  value: 5
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: latest
gradient_accumulation_steps:
  desc: null
  value: 100
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 500
lr_num_cycles:
  desc: null
  value: 1
lr_power:
  desc: null
  value: 1.0
use_8bit_adam:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: /mnt/g/data/output/lr2.56e-3_gas256
allow_tf32:
  desc: null
  value: false
report_to:
  desc: null
  value: wandb
mixed_precision:
  desc: null
  value: fp16
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
set_grads_to_none:
  desc: null
  value: false
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_data_dir:
  desc: null
  value: /mnt/d/data/dataset/spectrogram
image_column:
  desc: null
  value: image
conditioning_image_column:
  desc: null
  value: conditioning_image
caption_column:
  desc: null
  value: text
max_train_samples:
  desc: null
  value: null
proportion_empty_prompts:
  desc: null
  value: 0.5
num_validation_images:
  desc: null
  value: 1
validation_steps:
  desc: null
  value: 1
tracker_project_name:
  desc: null
  value: train_controlnet
only_mid_control:
  desc: null
  value: false
train_base:
  desc: null
  value: false
output_subdir_unet:
  desc: null
  value: unet
output_subdir_controlnet:
  desc: null
  value: controlnet
